version: "3.5"
services:
  whoami001:
    restart: always
    container_name: whoami001
    image: containous/whoami
    networks:
      - traefik
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.entrypoints=http,https
      - traefik.http.routers.whoami.rule=Host(`who.dev.run`)
      - traefik.http.routers.whoami.tls=true

  whoami002:
    restart: always
    container_name: whoami002
    image: containous/whoami
    networks:
      - traefik
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.entrypoints=http,https
      - traefik.http.routers.whoami.rule=Host(`who.dev.run`)
      - traefik.http.routers.whoami.tls=true

  whoami003:
    restart: always
    container_name: whoami003
    image: containous/whoami
    networks:
      - traefik
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.entrypoints=http,https
      - traefik.http.routers.whoami.rule=Host(`who.dev.run`)
      - traefik.http.routers.whoami.tls=true

networks:
  traefik:
    external: true
