version: "3"
services:
  rmqServer:
    restart: always
    image: foxiswho/rocketmq:4.7.0
    container_name: rocketmq-server
    networks:
      - traefik
    ports:
      - "9876:9876"
    volumes:
      - ./server/logs:/opt/logs
      - ./server/store:/opt/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -server -Xms256M -Xmx256M -Xmn128M"
    command: sh mqnamesrv
    labels:
      - traefik.enable=true
      - traefik.tcp.services.rmqServer.loadbalancer.server.port=9876
      - traefik.tcp.routers.rmqServer.entrypoints=rocketmq
      - traefik.tcp.routers.rmqServer.rule=HostSNI(`*`)
      - traefik.tcp.routers.rmqServer.tls=false

  rmqBroker001:
    restart: always
    image: foxiswho/rocketmq:4.7.0
    depends_on:
      - rmqServer
    networks:
      - traefik
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    volumes:
      - ./broker/broker.conf:/etc/rocketmq/broker.conf
      - ./broker/logs:/opt/logs
      - ./broker/store:/opt/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -server -Xms256M -Xmx256M -Xmn128M"
    command: sh mqbroker -c /etc/rocketmq/broker.conf -n rmqServer:9876
    labels:
      - traefik.enable=true
      - traefik.tcp.services.rmqBroker001.loadbalancer.server.port=10911
      - traefik.tcp.routers.rmqBroker001.entrypoints=rocketmq
      - traefik.tcp.routers.rmqBroker001.rule=HostSNI(`*`)
      - traefik.tcp.routers.rmqBroker001.tls=false

  rmqConsole:
    restart: always
    image: pongsky/rocketmq-console-ng
    container_name: rocketmq-console
    depends_on:
      - rmqServer
    networks:
      - traefik
    expose:
      - 8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqServer:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    volumes:
      - ./console:/tmp/rocketmq-console/data
    labels:
      - traefik.enable=true
      - traefik.http.services.rmqConsole.loadbalancer.server.port=8080
      - traefik.http.routers.rmqConsole.entrypoints=http,https
      - traefik.http.routers.rmqConsole.rule=Host(`rocketmq.dev.run`)
      - traefik.http.routers.rmqConsole.tls=true

networks:
  traefik:
    external: true
