version: "3.5"
services:
  traefik:
    restart: always
    container_name: traefik
    image: traefik:latest
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080" # ping
      # - "1001:1001" # mysql001
      # - "1002:1002" # mysql002
      - "2000:2000" # mongo
      - "3000:3000" # redis
      - "8000:8000" # rocketmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik:ro
      - ./config/tls:/config/tls:ro
    healthcheck:
      test: traefik healthcheck --ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  traefik:
    external: true
