version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    expose:
      - 8080
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik:ro
      - ./config/tls:/config/tls:ro
    networks:
      - net_traefik

networks:
  net_traefik:
    external: true
