providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    watch: true
    directory: /etc/traefik
    debugLogGeneratedTemplate: false

global:
  checkNewVersion: false
  sendAnonymousUsage: false

ping: {}

log:
  level: ERROR

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  # mysql001:
  #   address: ":1001"
  # mysql002:
  #   address: ":1002"
  mongo:
    address: ":2000"
  redis:
    address: ":3000"
  rocketmq:
    address: ":8000"
