providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
    debugLogGeneratedTemplate: true

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

api:
  dashboard: true
