version: "3"
services:
  gitlab:
    restart: always
    container_name: gitlab-ce
    image: gitlab/gitlab-ce:latest
    networks:
      - traefik
    expose:
      - 22
    ports:
      - "8001:80"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.com'
        nginx['listen_port'] = '80'
        nginx['listen_https'] = false

        registry_external_url 'https://reg.git.com'
        registry_nginx['listen_port'] = '80'
        registry_nginx['listen_https'] = false
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.entrypoints=http,https
      - traefik.http.routers.gitlab.rule=Host(`git.com`)
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.services.gitlab.loadbalancer.server.port=80

      - traefik.http.routers.registry.entrypoints=http,https
      - traefik.http.routers.registry.rule=Host(`reg.git.com`)
      - traefik.http.routers.registry.tls=true
      - traefik.http.routers.registry.service=registry
      - traefik.http.services.registry.loadbalancer.server.port=80

networks:
  traefik:
    external: true
