version: "3"
services:
  web:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-ce
    hostname: ${GITLAB_HOST}
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_HOST}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['http2_enabled'] = false
        nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
    expose:
      - 80
      - 443
    ports:
      - "0.0.0.0:22:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    labels:
      - "traefik.enable=true"
      # GitLab-Web
      - "traefik.gitlab.port=80"
      - "traefik.gitlab.frontend.rule=Host:${GITLAB_HOST}"
    networks:
      - net_traefik

networks:
  net_traefik:
    external: true
