version: "3"
services:
  runner001:
    restart: always
    container_name: gitlab_runner_001
    image: gitlab/gitlab-runner:latest
    networks:
      - traefik
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/etc/gitlab-runner/config.toml
      - ./ca.crt:/etc/gitlab-runner/certs/ca.crt

  runner002:
    restart: always
    container_name: gitlab_runner_002
    image: gitlab/gitlab-runner:latest
    networks:
      - traefik
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/etc/gitlab-runner/config.toml
      - ./ca.crt:/etc/gitlab-runner/certs/ca.crt

  runner003:
    restart: always
    container_name: gitlab_runner_003
    image: gitlab/gitlab-runner:latest
    networks:
      - traefik
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/etc/gitlab-runner/config.toml
      - ./ca.crt:/etc/gitlab-runner/certs/ca.crt

networks:
  traefik:
    external: true
